#!/bin/sh

. /usr/share/ganeti/extstorage/zfs/defaults.sh

# run lvchange for local vg only
if echo $* | grep -q $EXTP_VG ; then
	test -d /dev/$EXTP_VG || mkdir /dev/$EXTP_VG
	case $1 in
	-ay)
	VOL_NAME=`echo $2 | cut -d/ -f4`
	export VOL_NAME
	$dir/attach
	;;
	--addtag)
		VOL_NAME=`echo $3 | cut -d/ -f4`
		zfs set lv:tag=$2 $EXTP_ZFS/$VOL_NAME

		export EXTP_ZFS
		export VOL_NAME
		export VOL_METADATA=$2
		$dir/setinfo
	;;
	esac
else
	/sbin/lvm lvchange $*
fi
