#!/bin/sh -e

. /usr/share/ganeti/extstorage/zfs/defaults.sh

/sbin/lvm pvs $*

# pvs --noheadings --nosuffix --units=m --unbuffered '--separator=|' -opv_name,vg_name,pv_free,pv_attr,pv_size,pv_name

if echo $* | grep -q pv_name,vg_name,pv_free,pv_attr,pv_size,pv_name ; then

	zfs list $EXTP_ZFS -H -p -o avail,$EXTP_ZFS | sed "s:$EXTP_ZFS::" | awk '{ print "  '$EXTP_ZFS'|'$EXTP_VG'|" $1 / 1024 / 1024 "|a--|" ( $1 + $2 ) / 1024 / 1024 "|'$EXTP_ZFS'" }'

fi

